DandDCompany/Models/RoomViewModel.cs
using DandDCompany.Models;
using DTO.Entity;

namespace DandDCompany.Models
{
    public class RoomViewModel
    {
        public RoomViewModel() { }

        public Guid GameRoomId { get; set; }
        public string GameRoomName { get; set; }

        public Guid AccountId { get; set; }
        
        public string DiscriptionGameRoom { get; set; }

        public List<GamingSystemDTO> gamingSystemDTOs { get; set; } = new List<GamingSystemDTO>();
      
    }
}

DandDCompany/Controllers/CharacterRoomController.cs
using DataBase.DbEntity;
using DTO.Entity;
using DTO.Interface;
using Microsoft.AspNetCore.Mvc;

namespace DandDCompany.Controllers
{
    public class CharacterRoomController : Controller
    {
        private ICharacterRoomDTOService _characterRoomDTOService;
        public CharacterRoomController(ICharacterRoomDTOService characterRoomDTOService)
        {
            this._characterRoomDTOService = characterRoomDTOService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> PassAnswer( Guid gameRoomId,Guid gameCharId)
        {
            var characterRoom = await _characterRoomDTOService.GetFromCharacterIdandRoomId(gameCharId, gameRoomId);
    
            RoomDTO gameRoomDTO = new RoomDTO() { RoomId = characterRoom.RoomDTO.RoomId };
            CharacterDTO gameCharacterDTO = new CharacterDTO() {CharacterId = gameCharId };

            CharacterRoomDTO gameAccountGameRoomDTO = new CharacterRoomDTO()
            {               
                RoomDTO = gameRoomDTO,
                CharacterDTO = gameCharacterDTO,
                PassDTO = true,
            };
            await _characterRoomDTOService.Update(gameAccountGameRoomDTO);
            return RedirectToAction("GetAllRoom", "Room");
        }

        public async Task<IActionResult> RemoveByCharIdRoomId(Guid CharId,Guid RoomId)
        {
            await _characterRoomDTOService.RemoveByAccountIdRoomId(CharId,RoomId);
            return RedirectToAction("GetAllRoom", "Room");
        }
    }
}

DandDCompany/Controllers/RoomController.cs
using DandDCompany.Models;
using DataBase.DbEntity;
using DTO.Entity;
using DTO.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace DandDCompany.Controllers
{
    public class RoomController : Controller
    {
        private IRoomDTOService _roomDTOService;
        private ICharacterRoomDTOService _characterRoomDTOService;
        private IAccountDTOService _accountDTOService;
        private ICharacterDTOService _characterDTOService;
        private IGamingSystemDTOService _gamingSystemDTOService;
        private IGameClassDTOService _gameClassDTOService;

        public RoomController(IRoomDTOService roomDTOService,
            ICharacterRoomDTOService characterRoomDTOService,
            IAccountDTOService accountDTOService,
            ICharacterDTOService characterDTOService,
            IGamingSystemDTOService gamingSystemDTOService,
            IGameClassDTOService gameClassDTOService)
        {
            this._roomDTOService = roomDTOService;
            this._characterRoomDTOService = characterRoomDTOService;
            this._accountDTOService = accountDTOService;
            this._characterDTOService = characterDTOService;
            this._gamingSystemDTOService = gamingSystemDTOService;
            this._gameClassDTOService= gameClassDTOService;
        }
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> AddRoom(Guid AccountId)
        {
            var gamingSystem = await _gamingSystemDTOService.GetAll(); 
            RoomViewModel groupViewModel;
            groupViewModel = new RoomViewModel()
            {
                AccountId = AccountId,
                gamingSystemDTOs = gamingSystem
            };
            return View(groupViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> AddRoom(RoomViewModel groupViewModel,Guid GamingSystemId)
        {
            AccountDTO accountDTO = new AccountDTO() { AccountDTOId =groupViewModel.AccountId};
            GamingSystemDTO gamingSystemDTO = new GamingSystemDTO() {GamingSystemDTOId = GamingSystemId };
            RoomDTO groupDTO = new RoomDTO(groupViewModel.GameRoomId, accountDTO, groupViewModel.GameRoomName, gamingSystemDTO);
            await _roomDTOService.Add(groupDTO);
            return RedirectToAction("GetAllRoom", "Room");
        }

        public async Task<IActionResult> GetRoom(Guid id)
        {
            var room = await _roomDTOService.Get(id);

            var Account = await _accountDTOService.Get(room.AdminAccountDTO.AccountDTOId);
            room.AdminAccountDTO.MicrosoftAccountId = Account.MicrosoftAccountId;
            room.AdminAccountDTO.MicrosoftAccountName = Account.MicrosoftAccountName;

            List<CharacterDTO> gameAccountsDTOTrue = new List<CharacterDTO>();
            List<CharacterDTO> gameAccountsDTOFalse = new List<CharacterDTO>();

            foreach (var item in room.AccountRoomsDTO)
            {
                if (item.PassDTO == true)
                {
                    var character = await _characterDTOService.Get(item.CharacterDTO.CharacterId);
                  
                    Account = await _accountDTOService.Get(character.AccountDTO.AccountDTOId);
                    character.AccountDTO.MicrosoftAccountName = Account.MicrosoftAccountName;

                    gameAccountsDTOTrue.Add(character);
                }
                else
                {

                    var character = await _characterDTOService.Get(item.CharacterDTO.CharacterId);

                    Account = await _accountDTOService.Get(character.AccountDTO.AccountDTOId);
                    character.AccountDTO.MicrosoftAccountName = Account.MicrosoftAccountName;

                    gameAccountsDTOFalse.Add(character);
                }

            }

            room.CharacterDTOAnswerTrue = gameAccountsDTOTrue;
            room.CharacterDTOAnswerFalse = gameAccountsDTOFalse;

            return View(room);
        }

        public async Task<IActionResult> GetAllRoom()
        {
            var gameRoom = await _roomDTOService.GetAll();
            return View(gameRoom);
        }

        [HttpGet]
        public async Task<IActionResult> JoinTheRoom(Guid Roomid,string MicrosoftAccountId,Guid GamingSystem)
        {
            var account = await _accountDTOService.GetAccountForMicrosoftAccountId(Guid.Parse(MicrosoftAccountId)); 
            
            List<CharacterDTO> characterDTOs = new List<CharacterDTO>();
            GameClassDTO gameClass;

            foreach(var item in account.CharacterDTOs)
            {
                gameClass = await _gameClassDTOService.Get(item.GameClassDTO.GameClassDTOId);
                if(gameClass.GamingSystemDTO.GamingSystemDTOId == GamingSystem)
                {
                    characterDTOs.Add(item);
                }
           
            }

            RoomDTO RoomDTO = new RoomDTO() { RoomId = Roomid };
          
            CharacterRoomViewModel characterRoomViewModel;

            characterRoomViewModel = new CharacterRoomViewModel()
            {
                RoomDTO= RoomDTO,  
                Characters = characterDTOs
            };


            return View(characterRoomViewModel);
        }
            [HttpPost]
        public async Task<IActionResult> JoinTheRoom(CharacterRoomViewModel characterRoomViewModel,Guid GameCharId)
        {
            
            CharacterDTO gameCharacterDTO = new CharacterDTO() { CharacterId = GameCharId };

            bool pass = false;

            CharacterRoomDTO gameAccountGameRoomDTO = new CharacterRoomDTO(gameCharacterDTO,characterRoomViewModel.RoomDTO,pass);
            await _characterRoomDTOService.Add(gameAccountGameRoomDTO);
            return RedirectToAction("GetAllRoom", "Room");
        }
    }
}

DandDCompany/Views/Room/AddRoom.cshtml
@model RoomViewModel

<head>

    <style>




    </style>
</head>

<body>
    @if (@Model.GameRoomId == Guid.Empty)
    {

        <h1 style="text-align:center;font-weight: 400;">Add Game Room</h1>
        <hr />

    }
    else
    {
        <h1 style="text-align:center; font-weight: 400;"> Update Room</h1>
        <hr />
    }
    <div style="width:100%;">

        <form action="/Room/AddRoom" method="post">
            <div style="text-align:center">
                <p>
                    <div>
                        <h5 style="font-weight: 400;">
                            Enter Game Room Name:
                        </h5>

                    </div>

                    @Html.TextBoxFor(x => x.GameRoomName)
                    @Html.ValidationMessageFor(x=>x.GameRoomName)
                </p>

            </div>

            <div style="text-align:center;margin-bottom:20px;">
                <h5>Select GamingSystem</h5>

                <select name="GamingSystemId" id="AddRoom">
                    @foreach (var item in Model.gamingSystemDTOs)
                    {
                        <option value="@item.GamingSystemDTOId">@item.GamingSystemDTOName</option>
                    }
                </select>

            </div>

            @Html.HiddenFor(x=>x.GameRoomId)
            @Html.HiddenFor(q=>q.AccountId)
            @if (@Model.GameRoomId == Guid.Empty)
            {
                <div style="text-align:center">
                    <input type="submit" value="Add Game Room" />
                </div>
            }
            else
            {
                <div style="text-align:center">
                    <input type="submit" value="Update Game Room" />
                </div>
            }
        </form>
    </div>
</body>

DandDCompany/Views/Room/GetAllRoom.cshtml
@using DTO.Entity
@model List<RoomDTO>
<!doctype html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">


    <style>
   .top-buffer { margin-top:0px; }


        .background{
            background-color: #6f42c4;    
        }

        .background1 {
            background-color: #198754;
        }

        .background2 {
            background-color: #fd7e14;
        }
    </style>
  
</head>

<body>


    <div class="container background">

        <div class="row gy-3" style="text-align:center">
            <div class="col" >
                <div class="p-3 border bg-light">
                    Все созданные приключения
                </div>
              
            </div>
        
        </div>
     
        <div class="row gy-5 top-buffer " style="text-align:center">
           
            @foreach (var item in Model)
            {
                <div class="col-sm-4">

                    <div class="p-2 border bg-light ">
                        <h4 class="title"> @Html.ActionLink( @item.RoomName,"GetRoom","Room",new{@id = item.RoomId},new { @class = "menu-element" }) </h4>
                      
                    </div>


                </div>
            }
        </div>
        
        <div class="row gy-3" style="text-align:center">
            <div class="col">
                <div class="p-3 ">              
                </div>
            </div>

        </div>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</body>
</html>

DandDCompany/Views/Room/GetRoom.cshtml
@using DTO.Entity
@using System.Security.Claims;
@model RoomDTO

<!doctype html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">


    <style>
        .top-buffer {
            margin-top: 0px;
        }


        .background {
            background-color: #6f42c4;
        }

    </style>

</head>

<body>


    <div class="container background">

        <div class="row gy-3" style="text-align:center">
            <div class="col">
                <div class="p-3 border bg-light">
                    Информация про группу
                </div>

            </div>

        </div>

        <div class="row gy-5 top-buffer " style="text-align:center">


            <div class="col-sm-4">

                <div class="p-2 border bg-light ">
                    Назвагие группы:@Model.RoomName
                </div>
                <div class="p-2 border bg-light ">
                    Игровая система: @Model.GamingSystemDTO.GamingSystemDTOName
                </div>
                <div class="p-2 border bg-light ">
                    Описание группы:
                </div>
                <div class="p-2 border bg-light ">

                    Админ Группы: @Model.AdminAccountDTO.MicrosoftAccountName


                </div>
                <div class="p-2 border bg-light">
                    Участники группы : @foreach (var item in Model.CharacterDTOAnswerTrue)
                    {

                        <div class="col-sm-4" style="text-align:center">
                            @item.AccountDTO.MicrosoftAccountName
                            и его персонаж: @item.CharacterName
                            @if (Model.AdminAccountDTO.MicrosoftAccountId == Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value))
                            {
                                @Html.ActionLink("Обновить персонажа","AddCharacter","Character",new{@CharId =item.CharacterId})
                            }


                        </div>
                    }

                </div>
                <div class="p-2 border bg-light">
                    Участники ожидающие вступление в группу :
                    @foreach (var item in Model.CharacterDTOAnswerFalse)
                    {
                        <div class="col-sm-4" style="text-align:center">

                            @item.AccountDTO.MicrosoftAccountName
                            и его персонаж:
                            @item.CharacterName

                            @if ((Model.AdminAccountDTO.MicrosoftAccountId).ToString() == User.FindFirst(ClaimTypes.NameIdentifier).Value)
                            {
                                @Html.ActionLink("Принять в группу","PassAnswer","CharacterRoom",new{@gameRoomId = Model.RoomId,@gameCharId= item.CharacterId})
                            }

                            @if ((Model.AdminAccountDTO.MicrosoftAccountId).ToString() == User.FindFirst(ClaimTypes.NameIdentifier).Value)
                            {
                                @Html.ActionLink(" Отказать на вступление в группу","RemoveByCharIdRoomId","CharacterRoom",new{@CharId = item.CharacterId,RoomId = Model.RoomId})
                            }

                            else
                            {
                                @Html.ActionLink("Выйти из листа ожидания","RemoveByAccountIdRoomId","CharacterRoom",new{@CharId = item.CharacterId,RoomId = Model.RoomId})
                            }


                        </div>

                    }
                </div>

            </div>

            <div class="row gy-3" style="text-align:center">
                <div class="col">
                    <div class="p-3 ">
                    </div>
                </div>

            </div>
        </div>
        @if (Model.AdminAccountDTO.MicrosoftAccountId != Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value))
        {
            @Html.ActionLink("JoinGameRoom","JoinTheRoom","Room",new{@Roomid = Model.RoomId,@MicrosoftAccountId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value,@GamingSystem = Model.GamingSystemDTO.GamingSystemDTOId})

        }


    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</body>
</html>

DandDCompany/Views/Room/JoinTheRoom.cshtml
@model CharacterRoomViewModel




<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
    <style>




    </style>
</head>

<body>
    

        <h1 style="text-align:center;font-weight: 400;">Выбери персонажа для входды в группу </h1>
        <hr />

   
    <div style="width:100%;">

        <form action="/Room/JoinTheRoom" method="post">
         

            <div style="text-align:center;margin-bottom:20px;">
                         
                <select name="GameCharId" id="JoinTheRoom">
                    @foreach (var item in Model.Characters)
                    {
                        <option value="@item.CharacterId">@item.CharacterName</option>
                    }
                </select>
            </div>
            <div style="text-align:center">
                <input type="submit" value="Add Group" />
            </div>

            @Html.HiddenFor(q=>q.RoomDTO.RoomId)
        </form>
    </div>
</body>